from base64 import b32decode
from utils.basics import hex_to_ascii
from utils.cryptography.phone_keypad import decode_keypad

enc = b"GBQSAMTCEAZGEIBSMIQDEYRAGJRCAMTCEAZGEIBSMIQDEYRAGJRCANLCEAZWKIBSMIQDGZJAGJRCAMTCEAZGEIBTMUQDEYRAGJRCAMTCEAZGEIBSMIQDEYRAGJRCAM3FEAZGEIBSMIQDEYRAGJRCAMTCEAZGEIBSMIQDEYRAGJRCAMTCEAZWGIBTMMQDGYZAGNRSAMTEEA2WIIBTMUQDGZJAGNSSAMTCEAZGEIBSMIQDEYRAGJRCAMTCEAZGEIBSMIQDEZJAGJSCAMTEEAZGKIBSMIQDEYRAGJRCAMTCEAZGEIBSMUQDEZBAGJSCAMTEEAZGIIBSMQQDEZBAGJSCAMTEEAZGIIBSMUQDEYRAGJRCAMTCEAZGEIBSMIQDEYRAGJRCAMTCEAZGKIBSMIQDEYRAGJRCAMTCEAZGEIBSMIQDEYRAGJRCAMTCEAZGEIBSMUQDEZBAGJSCAMTEEAZGIIBSMQQDEZBAGJSCAMTEEAZGIIBSMQQDEZBAGJSCAMTEEAZGIIBSMUQDGZJAGJRCAMTCEAZGEIBSMIQDEYRAGJRCAMTCEAZGEIBSMIQDEYRAGJRCAMTCEAZGEIBSMIQDEYRAGJRCAMTCEAZGEIBSMIQDEYRAGJRCAMTCEAZGEIBSMUQDGYZAGJRCAMTCEAZGEIBSMIQDEYRAGJRCAMTFEAZWGIBSMIQDEYRAGJRCAMTCEAZGEIBSMIQDEYRAGJRCAMTCEAZGEIBSMIQDEYRAGJRCAMTCEAZGEIBSMIQDEYRAGJRCAMTFEAZGKIBTMUQDEZBAGJSCAMTEEAZGIIBSMQQDEZBAGJSCAMTEEAZGIIBSMQQDEZJAGJRCAMTCEAZGEIBSMIQDEYRAGJRCAMTCEAZGEIBSMIQDEYRAGJRCAMTCEAZGEIBSMIQDEYRAGJRCAMTCEAZGEIBSMIQDEYRAGJRCAMTCEAZGEIBSMUQDEZBAGJSCAMTEEAZGIIBSMQQDEZJAGNRSAMTFEAZGEIBSMUQDGZJAGJSCAMTEEAZGIIBSMQQDEZBAGJSCAMTEEAZGIIBSMQQDEZBAGJSCAMTEEAZGIIBSMQQDEZBAGJSCAMTEEAZGIIBSMQQDEZJAGJRCAMTCEAZGEIBSMIQDEZJAGNSSAMTCEAZGEIBSMU======"
enc = b32decode(enc).decode()
enc = hex_to_ascii(enc)
print(enc.strip())
enc = "NLQHPZL{R00H_Z01GK}"
print(enc)


key = ""

with open("key-enc.txt") as f:
    for line in f:
        line = line.strip()
        if line.startswith('-'):
            binary = line.replace('-----', '0').replace('.----', '1').replace(' ', '')
            key += chr(int(binary, 2))
        else:
            continue

print(key)

key = hex_to_ascii(key)
key = decode_keypad(key)

# RESTCON{G00D_G01NG}